project: 
  type: website

website: 
  page-navigation: true
  title: "Long-term Monitoring at an Oyster Farm in Southeast AK" 
  site-url: "https://afscmariculture.github.io/oyster_report/" 
  repo-url: "https://github.com/afscmariculture/oyster_report.git"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  sidebar:
    background: "#D9E3E4"
    logo: "https://user-images.githubusercontent.com/67389727/202267118-43e3d083-46d2-456c-99bf-11bf3aae7160.png"
    
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.fisheries.noaa.gov/about/alaska-fisheries-science-center
        text: "NOAA Alaska Fisheries Science Center"
      - icon: github
        href: https://github.com/afscmariculture
        text: "AFSC Mariculture Team"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/environmental_conditions.qmd
        text: Environmental Conditions
      - href: content/phytoplankton.qmd
        text: Phytoplankton Community Composition
      - href: content/oysters.qmd
        text: Oyster Health and Toxicity
      - href: content/phyto_photos.qmd
        text: Phytoplankton Photos
      - href: content/acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
